name: walleto
description: "An Application for managing wallets, transactions"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  

  # Firebase
  firebase_core: 3.14.0
  firebase_messaging: 15.2.7

  # Local storage
  shared_preferences: 2.5.3
  flutter_secure_storage: 9.2.4

  # State management
  flutter_bloc: 9.1.1

  # UI
  flutter_svg: 2.2.0
  cupertino_icons: 1.0.8
  infinite_scroll_pagination: 4.1.0
  shimmer: 3.0.0
  carousel_slider: 5.1.1
  fl_chart: 1.0.0
  lottie: 3.3.1

  # DI
  get_it: 8.0.3
  injectable: 2.5.0

  # Utils
  freezed_annotation: 3.0.0
  json_annotation: 4.9.0
  async: 2.12.0
  flutter_local_notifications: 19.2.1
  path_provider: 2.1.5
  dartx: 1.2.0
  device_info_plus: 11.5.0
  rxdart: 0.28.0
  auto_route: 10.1.0
  intl: 0.19.0
  permission_handler: 12.0.0+1
  package_info_plus: 8.3.0
  flutter_app_badge: 2.0.2
  app_links: 6.4.0
  flutter_screenutil: 5.9.3
  uuid: 4.5.1
  android_intent_plus: 5.3.0
  local_auth: 2.3.0
  local_auth_android: 1.0.49
  local_auth_darwin: 1.4.3
  flutter_widget_from_html: 0.16.0
  timezone: 0.10.1
  media_scanner: 2.2.0

  # Networking
  dio: 5.8.0+1
  dio_cookie_manager: 3.2.0
  cookie_jar: 4.0.8
  connectivity_plus: 6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 5.0.0
  build_runner: 2.5.1
  flutter_gen_runner: 5.10.0
  auto_route_generator: 10.1.0
  freezed: 3.0.6
  json_serializable: 6.9.5
  injectable_generator: 2.7.0
  flutter_native_splash: 2.4.6
  flutter_launcher_icons: 0.14.4
  intl_utils: 2.8.10

# fluttergen
flutter_gen:
  output: lib/resources/gen
  line_length: 100

  integrations:
    flutter_svg: true
    lottie: true

# dart run flutter_launcher_icons:main
flutter_launcher_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: assets/images/walleto_logo.png
  adaptive_icon_background: assets/images/adaptive-icon.png

# dart run flutter_native_splash:create
flutter_native_splash:
  ios: true
  android: true
  fullscreen: true
  image: assets/images/walleto_splash_screen.png
  color: "#050506"
  # background_image: assets/images/.png
  android_12:
    color: "#050506"

# dart run intl_utils:generate
flutter_intl:
  enabled: true
  main_locale: en_US
  output_dir: lib/resources/l10n/generated
  arb_dir: lib/resources/l10n

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/

  fonts:
    - family: SpaceGrotesk
      fonts:
        - asset: assets/fonts/SpaceGrotesk-Regular.ttf
          weight: 400
        - asset: assets/fonts/SpaceGrotesk-Medium.ttf
          weight: 500
        - asset: assets/fonts/SpaceGrotesk-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SpaceGrotesk-Bold.ttf
          weight: 700
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/DMSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/DMSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DMSans-Bold.ttf
          weight: 700
