create table if not exists public.ai_chat_messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role = any (array['user'::text, 'assistant'::text])),
  content text not null,
  model text,
  prompt_tokens integer,
  completion_tokens integer,
  total_tokens integer,
  created_at timestamptz not null default now()
);

create index if not exists idx_ai_chat_messages_user_created_at
  on public.ai_chat_messages using btree (user_id, created_at desc);

alter table public.ai_chat_messages enable row level security;

drop policy if exists "Users can read own ai chat messages" on public.ai_chat_messages;
create policy "Users can read own ai chat messages"
  on public.ai_chat_messages
  for select
  using (auth.uid() = user_id);

drop policy if exists "Users can insert own ai chat messages" on public.ai_chat_messages;
create policy "Users can insert own ai chat messages"
  on public.ai_chat_messages
  for insert
  with check (auth.uid() = user_id);

drop policy if exists "Users can delete own ai chat messages" on public.ai_chat_messages;
create policy "Users can delete own ai chat messages"
  on public.ai_chat_messages
  for delete
  using (auth.uid() = user_id);

grant select, insert, delete on table public.ai_chat_messages to authenticated;
